CREATE TYPE user_status AS ENUM ('ACTIVE', 'LOCKED', 'DELETED');
CREATE TYPE stop_type AS ENUM('PICKUP', 'STOP', 'DELIVERED', 'DELIVERY', 'CONSIGNEE');
CREATE TYPE asset_type AS ENUM('VAN', 'TRUCK', 'TRAILER', 'FLAT');
CREATE TYPE role_status AS ENUM('INVALID', 'ISSUED', 'PENDING', 'REJECTED', 'REAPPLY', 'INFO_REQUESTED', 'CONTACT_REQUESTED', 'ASSIGNED', 'TEMPORARY', 'ABSENCE', 'ACCEPTED', 'SUSPENDED', 'TERMINATED');
CREATE TYPE scope_type AS ENUM('COMPANY', 'WRAPPER', 'CONTACT', 'CARRIER', 'APP', 'SYSTEM');