CREATE SCHEMA IF NOT EXISTS general;

CREATE TABLE general.assets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    public_id uuid DEFAULT gen_random_uuid(),
    created_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_by uuid,
    kind_id uuid,
    image_id uuid,
    status_id uuid,
    location_id uuid,
    trailer_type_id uuid,
    external_number character varying(256),
    make character varying(256),
    model character varying(256),
    color character varying(256),
    year integer,
    weight numeric(16,10),
    registration_number character varying(256),
    registration_state character varying(256),
    registration_date text,
    starting_miles numeric(20,10),
    starting_zip character varying(256),
    length numeric(16,10),
    current_miles numeric(20,10),
    weight_capacity numeric(16,10),
    support_air_ride boolean,
    metadata json,
    asset_type public.asset_type,
    vin_number text,
    trailer_truck boolean,
    truck_number text,
    trailer_number text,
    license_plate text,
    current_location character varying(100),
    status_toggle boolean,
    company_id uuid,
    asset_id uuid,
    ip text,
    ip_info text,
    asset_number text,
    last_location text,
    created_on character varying(100),
    updated_on character varying(100),
    is_boxtruck boolean,
    created_by_external uuid,
    updated_by_external uuid
);


CREATE TRIGGER sync_lastmod BEFORE UPDATE ON general.assets FOR EACH ROW EXECUTE FUNCTION public.sync_lastmod();