CREATE SCHEMA IF NOT EXISTS general;

CREATE TABLE general.commodity (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    public_id uuid DEFAULT gen_random_uuid(),
    created_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_by uuid,
    name text,
    type text,
    quantity integer,
    piece_count integer,
    length numeric(12,6),
    width numeric(12,6),
    height numeric(12,6),
    weight numeric(12,6),
    volume numeric(12,6),
    density numeric(12,6),
    class text,
    nmfc text,
    external_number integer,
    weight_unit_type text,
    dimensions_unit_type text,
    is_stackable boolean,
    is_truckload boolean,
    description text,
    note uuid,
    oversized boolean,
    hazmat boolean,
    cases integer,
    pallets integer,
    pallets_exchange boolean,
    temperature_range text,
    container_number text,
    value integer,
    ip text,
    ip_info text,
    created_on character varying(100),
    updated_on character varying(100),
    created_by_external uuid,
    updated_by_external uuid
);

CREATE TRIGGER sync_lastmod BEFORE UPDATE ON general.commodity FOR EACH ROW EXECUTE FUNCTION public.sync_lastmod();